{{- if and .Values.manager.secret.enabled (gt (len .Values.manager.secret.stringData) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (printf "%s-manager-env" (include "hiclaw.fullname" .)) .Values.manager.secret.name }}
  namespace: {{ include "hiclaw.namespace" . }}
  labels:
    {{- include "hiclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.manager.secret.stringData }}
  {{ $k }}: {{ $v | toString | quote }}
{{- end }}
{{- end }}
