apiVersion: v1
kind: Service
metadata:
  name: {{ include "hiclaw.fullname" . }}
  namespace: {{ include "hiclaw.namespace" . }}
  labels:
    {{- include "hiclaw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.manager.service.type }}
  selector:
    {{- include "hiclaw.selectorLabels" . | nindent 4 }}
  ports:
    - name: openclaw
      port: {{ .Values.manager.service.port }}
      targetPort: {{ .Values.manager.service.targetPort }}
      protocol: TCP
