{{- if .Values.workerServiceAccount.create }}
{{- $wrrsaWebhook := and .Values.workerServiceAccount.rrsa.enabled (eq (.Values.workerServiceAccount.rrsa.mode | default "manual") "webhook") .Values.workerServiceAccount.rrsa.roleName }}
{{- $wsaExtraAnn := .Values.workerServiceAccount.annotations | default dict }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hiclaw.workerServiceAccountName" . }}
  namespace: {{ include "hiclaw.namespace" . }}
  labels:
    app.kubernetes.io/component: hiclaw-worker
    {{- include "hiclaw.labels" . | nindent 4 }}
  {{- if or $wrrsaWebhook (gt (len $wsaExtraAnn) 0) }}
  annotations:
    {{- if $wrrsaWebhook }}
    pod-identity.alibabacloud.com/role-name: {{ .Values.workerServiceAccount.rrsa.roleName | quote }}
    {{- end }}
    {{- range $k, $v := $wsaExtraAnn }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
{{- end }}
